<div class="search-result">
<?php $documents = $block->getDocuments(); ?>
<?php if ($documents && sizeof($documents)): ?>
    <div class="documents">       
            <?php
            foreach ($documents as $document): ?>  
            <?php  //echo json_encode($document->getData()); ?>         
                <div class="pdf-main">
                <?php 
                 $fileUrl = '#';
                if($document->getAttachmentType() == 0){
                    $fileUrl = $block->getFileUrl('amasty/amfile/attach/'.$document->getFilepath());
                }else{
                    $fileUrl = $document->getFilepath();
                }         
                ?>                
                <a href="<?php echo $fileUrl;?>" class="am-filelink <?php echo $document->getAmastyFileId()?>" target="_blank">
                    <div class="pdf-img">
                        <img src="<?php echo $block->getFileIcon($document->getExtension(),$document->getAttachmentType());?>" class="am-fileicon" alt="document">
                    </div>
                    <div class="pdf-content">
                        <div class="brand-name">                          
                            <?php echo __($document->getManufacturer()); ?>     
                        </div>
                        <p class="product-name">
                            <?php echo __($document->getData('filename')); ?>     
                        </p>
                        <?php if($document->getSku()):?>
                        <div class="model">
                            <?php echo __('Model :'); ?>
                            <?php echo __($document->getSku()); ?>                           
                        </div>
                        <?php endif;?>
                        <?php if($document->getEquipmentType()):?>
                        <div class="equiptment">                        
                            <?php echo __('Equipment :');?>
                            <?php
                             $eq= '';
                            if( strpos($document->getEquipmentType(), ',') !== false ) {
                                $eqArray = array_filter(array_unique(explode(",",(string)$document->getEquipmentType())));
                                 $eq =implode(',',$eqArray);
                           } else {
                            $eq = $document->getEquipmentType();
                           }
                            ?>
                            <?php echo __( $eq); ?>
                        </div>
                        <?php endif;?>
                    </div>
                    </a>
                </div>               
            <?php endforeach; ?>
      </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No Document found.'); ?></span></div>
<?php endif ?>
</div>

